version: "3"
services:
  broker:
    image: broadcaster:latest
    container_name: broadcaster
    ports:
    - "8081:8081"
    expose:
      - 8081
    environment:
      CONTAINER_NAME: localhost

  nba:
    image: nba:latest
    container_name: nba
    ports:
    - "8082:8082"
    environment:
      CONTAINER_NAME: localhost

  soccer:
    image: soccer:latest
    container_name: soccer
    ports:
    - "8083:8083"
    environment:
      CONTAINER_NAME: localhost


